'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { request } from '../lib/client';
import type { AiRun,catalogEvidence } from '@commerce/ai';
type Output={id:string;text:string;mode:string;evidence:Awaited<ReturnType<typeof catalogEvidence>>};
const date=(v:string)=>new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}).format(new Date(v));
export function AiWorkspace({tenantId,shopId,liveEnabled,initialRuns}:{tenantId:string;shopId:string;liveEnabled:boolean;initialRuns:(Omit<AiRun,'created_at'>&{created_at:string})[]}){
 const [question,setQuestion]=useState('สรุปรายการสินค้าในร้านนี้'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[output,setOutput]=useState<Output|null>(null);const router=useRouter();
 async function run(mode:'tool-preview'|'live'){setBusy(true);setError('');setOutput(null);try{setOutput(await request(`/api/tenants/${tenantId}/ai`,{shopId,question,mode}));router.refresh();}catch(e){setError(e instanceof Error?e.message:'ไม่สำเร็จ');}finally{setBusy(false);}}
 return <><div className="page-heading"><div><h1>วิเคราะห์ข้อมูล</h1><p>ข้อมูลจากร้านที่เลือก</p></div></div><div className="ai-grid"><section className="panel"><h2>ตรวจรายการสินค้า</h2><p className="field-help">ดูจำนวน SKU หมวดสินค้า และรายการอ้างอิงที่คุณเข้าถึงได้</p>{liveEnabled?<label>คำถาม<textarea value={question} onChange={e=>setQuestion(e.target.value)} maxLength={1000} rows={3}/></label>:<p className="notice">ยังไม่ได้เชื่อมต่อโมเดล AI ขณะนี้ตรวจรายการสินค้าโดยตรงได้ แต่ยังวิเคราะห์ยอดขายหรือกำไรไม่ได้</p>}<div className="ai-actions"><button className="button secondary" disabled={busy} onClick={()=>run('tool-preview')}>{busy?'กำลังตรวจ…':'ตรวจรายการสินค้า'}</button>{liveEnabled&&<button className="button primary" disabled={busy||!question.trim()} onClick={()=>run('live')}>วิเคราะห์ด้วย AI</button>}</div>{error&&<p className="notice error" role="alert">{error}</p>}{output&&<div className="ai-result" role="status"><p className="result-text">{output.text}</p><div className="evidence"><h3>รายการอ้างอิง</h3><ul>{output.evidence.examples.map(e=><li key={e.evidenceRef}><span>{e.name}</span><code>{e.sku}</code></li>)}</ul><small>ตรวจเมื่อ {date(output.evidence.asOf)} · {output.mode==='tool-preview'?'ผลจากระบบ ไม่ได้เรียกโมเดล AI':'คำตอบจากโมเดล AI'}</small></div></div>}</section><aside className="panel"><h2>ประวัติการตรวจ</h2>{initialRuns.length?initialRuns.map(r=><details className="run-row" key={r.id}><summary><span>{date(r.created_at)}</span><span>{r.status==='succeeded'?'สำเร็จ':r.status==='failed'?'ไม่สำเร็จ':'กำลังทำงาน'}</span></summary><small>{r.mode==='tool-preview'?'ตรวจรายการโดยระบบ':'วิเคราะห์ด้วย AI'}</small>{r.result&&<p>{r.result.text}</p>}</details>):<p className="quiet-empty">ยังไม่มีประวัติ</p>}</aside></div></>;
}
