'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect,useRef,useState } from 'react';
import { ArrowRight,CheckCircle2,RotateCcw,X } from 'lucide-react';
import type { ExpenseAllocationScope,ShopExpenseItem,ShopExpenseLedger,ShopExpenseType } from '@commerce/finance';
import { money,request,toMinor } from '../lib/client';

export const expenseLabels:Record<ShopExpenseType,string>={advertising:'ค่าโฆษณา',shipping:'ค่าขนส่งที่ร้านออกเอง',packaging:'ค่าแพ็กและบรรจุภัณฑ์',payroll:'เงินเดือนและแรงงาน',travel:'เดินทางและน้ำมัน',other:'ค่าใช้จ่ายอื่น'};
const date=(value:string)=>new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date(`${value}T00:00:00+07:00`));

function ExpenseStatus({item}:{item:ShopExpenseItem}){
  if(item.reversesExpenseId)return <span className="pill neutral">รายการแก้กลับ</span>;
  if(item.reversedByExpenseId)return <span className="pill neutral">ถูกแก้กลับแล้ว</span>;
  return <span className="pill green">มีผลต่อยอดรวม</span>;
}

export function ExpenseWorkspace({tenantId,shopId,shopName,canWrite,today,initialReference,ledger}:{tenantId:string;shopId:string;shopName:string;canWrite:boolean;today:string;initialReference:string;ledger:ShopExpenseLedger}){
  const router=useRouter(),[expenseType,setExpenseType]=useState<ShopExpenseType>('advertising'),[sourceExpenseId,setSourceExpenseId]=useState(initialReference),[occurredOn,setOccurredOn]=useState(today),[amount,setAmount]=useState(''),[allocationScope,setAllocationScope]=useState<ExpenseAllocationScope>('shop_direct'),[allocationBasis,setAllocationBasis]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
  const [reversing,setReversing]=useState<ShopExpenseItem|null>(null),[reversalDate,setReversalDate]=useState(today),[reversalNote,setReversalNote]=useState(''),[reversalConfirmed,setReversalConfirmed]=useState(false),[reversalBusy,setReversalBusy]=useState(false),[reversalError,setReversalError]=useState(''),[reversalSaved,setReversalSaved]=useState('');
  const reversalNoteRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{if(reversing){document.getElementById('expense-reversal-entry')?.scrollIntoView({block:'center'});reversalNoteRef.current?.focus();}},[reversing]);

  async function submit(event:React.FormEvent){
    event.preventDefault();setError('');setSaved('');setBusy(true);
    try{
      const amountMinor=toMinor(amount.trim());if(amountMinor<=0)throw new Error('จำนวนเงินต้องมากกว่า 0 บาท');
      const result=await request<{duplicate:boolean}>(`/api/tenants/${tenantId}/expenses`,{shopId,sourceExpenseId:sourceExpenseId.trim(),expenseType,occurredOn,amountMinor,allocationScope,allocationBasis:allocationScope==='shared_allocated'?allocationBasis.trim():null,note:note.trim(),confirmedOutsideImportedReceipt:confirmed});
      setSaved(result.duplicate?'เอกสารอ้างอิงนี้ถูกบันทึกไว้แล้ว ระบบไม่ได้เพิ่มยอดซ้ำ':'บันทึกค่าใช้จ่ายแล้วและนำไปคำนวณในหน้าผลประกอบการ');
      if(!result.duplicate){setSourceExpenseId(`EXP-${crypto.randomUUID()}`);setAmount('');setAllocationScope('shop_direct');setAllocationBasis('');setNote('');setConfirmed(false);}router.refresh();
    }catch(e){setError(e instanceof Error?e.message:'บันทึกค่าใช้จ่ายไม่สำเร็จ');}finally{setBusy(false);}
  }

  function selectReversal(item:ShopExpenseItem){setReversing(item);setReversalDate(today);setReversalNote('');setReversalConfirmed(false);setReversalError('');setReversalSaved('');}
  async function submitReversal(event:React.FormEvent){
    event.preventDefault();if(!reversing)return;setReversalError('');setReversalSaved('');setReversalBusy(true);
    try{
      const result=await request<{duplicate:boolean}>(`/api/tenants/${tenantId}/expenses/${reversing.id}/reverse`,{shopId,occurredOn:reversalDate,note:reversalNote.trim(),confirmedCorrection:reversalConfirmed});
      setReversalSaved(result.duplicate?'รายการแก้กลับนี้ถูกบันทึกไว้แล้ว ระบบไม่ได้เพิ่มยอดซ้ำ':`แก้กลับ ${expenseLabels[reversing.expenseType]} แล้ว รายการเดิมยังอยู่ในประวัติ`);setReversing(null);router.refresh();
    }catch(e){setReversalError(e instanceof Error?e.message:'แก้กลับค่าใช้จ่ายไม่สำเร็จ');}finally{setReversalBusy(false);}
  }

  const categoryMap=new Map(ledger.categoryTotals.map(row=>[row.expenseType,row.amountMinor])),activeCategories=ledger.categoryTotals.filter(row=>row.amountMinor>0).length;
  return <>
    <div className="page-heading"><div><h1>ค่าใช้จ่ายร้าน</h1><p>{shopName} · ค่าใช้จ่ายที่จ่ายแยกจากยอดเงินรับในรายงานขาย</p></div><Link className="button secondary" href="/performance">ดูเงินรับและต้นทุน <ArrowRight size={16}/></Link></div>
    <section className="summary-strip adjustment-overview" aria-label="สรุปค่าใช้จ่ายร้าน"><div><span>ค่าใช้จ่ายที่ยังมีผล</span><strong className={ledger.summary.activeAmountMinor?'text-error':''}>{money(ledger.summary.activeAmountMinor)}</strong></div><div><span>รายการที่ยังมีผล</span><strong>{ledger.summary.activeExpenseCount}<small>รายการ</small></strong></div><div><span>หมวดที่มีค่าใช้จ่าย</span><strong>{activeCategories}<small>หมวด</small></strong></div><div><span>แก้กลับแล้ว</span><strong>{ledger.summary.reversedExpenseCount}<small>รายการ</small></strong></div></section>
    {reversalSaved&&<p className="notice success" role="status">{reversalSaved}</p>}
    <section className="panel expense-category-panel"><div className="panel-heading"><div><h2>ยอดตามหมวด</h2><p className="field-help">รวมเฉพาะรายการที่ยังมีผล ระบบไม่กระจายยอดไปยังคำสั่งซื้อหรือ SKU โดยอัตโนมัติ</p></div></div><dl className="expense-category-grid">{(Object.keys(expenseLabels) as ShopExpenseType[]).map(type=><div key={type}><dt>{expenseLabels[type]}</dt><dd>{money(categoryMap.get(type)??0)}</dd></div>)}</dl></section>
    {!canWrite&&<p className="notice">สิทธิ์ผู้ตรวจสอบเปิดดูยอดและหลักฐานได้ การบันทึกหรือแก้กลับต้องใช้สิทธิ์เจ้าของหรือการเงิน</p>}
    {canWrite&&<section className="panel financial-event-entry"><div><h2>บันทึกค่าใช้จ่าย</h2><p className="field-help">บันทึกเฉพาะยอดที่จ่ายแยกและยังไม่อยู่ในเงินรับสุทธิจากไฟล์ เช่น ค่าโฆษณา เงินเดือน หรือน้ำมัน</p></div><form onSubmit={submit}><div className="financial-event-fields"><label>หมวดค่าใช้จ่าย<select value={expenseType} disabled={busy} onChange={e=>setExpenseType(e.target.value as ShopExpenseType)}>{(Object.keys(expenseLabels) as ShopExpenseType[]).map(type=><option value={type} key={type}>{expenseLabels[type]}</option>)}</select></label><label>วันที่เกิดค่าใช้จ่าย<input type="date" value={occurredOn} max="2100-12-31" required disabled={busy} onChange={e=>setOccurredOn(e.target.value)}/></label><label>จำนวนเงิน (บาท)<input aria-label="จำนวนเงินค่าใช้จ่าย (บาท)" inputMode="decimal" value={amount} required placeholder="0.00" disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label>เอกสารอ้างอิง<input aria-label="เอกสารอ้างอิงค่าใช้จ่าย" value={sourceExpenseId} maxLength={150} required disabled={busy} onChange={e=>setSourceExpenseId(e.target.value)}/><span className="field-help">ระบบสร้างให้ แก้เป็นเลขใบเสร็จหรือเลขรายงานโฆษณาได้</span></label><label>ค่าใช้จ่ายนี้เป็นของใคร<select aria-label="ขอบเขตค่าใช้จ่าย" value={allocationScope} disabled={busy} onChange={e=>setAllocationScope(e.target.value as ExpenseAllocationScope)}><option value="shop_direct">ของร้านนี้โดยตรง</option><option value="shared_allocated">ค่าใช้จ่ายส่วนกลางที่แบ่งให้ร้านนี้</option></select></label>{allocationScope==='shared_allocated'&&<label>วิธีแบ่งค่าใช้จ่าย<input aria-label="วิธีแบ่งค่าใช้จ่ายส่วนกลาง" value={allocationBasis} minLength={3} maxLength={300} required placeholder="เช่น 40% ตามสัดส่วนยอดขายเดือนนี้" disabled={busy} onChange={e=>setAllocationBasis(e.target.value)}/><span className="field-help">กรอกเฉพาะยอดที่แบ่งให้ร้านนี้แล้ว</span></label>}<label className="full-width">รายละเอียดหรือหลักฐาน<input aria-label="รายละเอียดค่าใช้จ่าย" value={note} minLength={3} maxLength={500} required placeholder="เช่น ค่าโฆษณา TikTok รอบวันที่ 1–15 ก.ย." disabled={busy} onChange={e=>setNote(e.target.value)}/></label></div><label className="checkbox-label financial-scope-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>ฉันตรวจแล้วว่ายอดนี้จ่ายแยกและยังไม่รวมอยู่ในเงินรับสุทธิหรือรายการค่าใช้จ่ายอื่น จึงไม่ถูกหักซ้ำ</label>{error&&<p className="notice error" role="alert">{error}</p>}{saved&&<p className="notice success" role="status">{saved}</p>}<div className="form-actions"><button type="submit" className="button primary" disabled={busy||!confirmed||!sourceExpenseId.trim()||!occurredOn||!amount.trim()||note.trim().length<3||(allocationScope==='shared_allocated'&&allocationBasis.trim().length<3)}>{busy?'กำลังบันทึก…':'บันทึกค่าใช้จ่าย'}</button></div></form></section>}
    {canWrite&&reversing&&<section className="panel reversal-entry" id="expense-reversal-entry" aria-labelledby="expense-reversal-heading"><div className="reversal-heading"><div><span className="eyebrow">แก้ไขโดยเก็บหลักฐานเดิม</span><h2 id="expense-reversal-heading">แก้กลับค่าใช้จ่าย</h2><p>ระบบจะยกเลิกผลของ {expenseLabels[reversing.expenseType]} จำนวน {money(reversing.amountMinor)}</p></div><button type="button" className="icon-button" aria-label="ยกเลิกการแก้กลับ" disabled={reversalBusy} onClick={()=>setReversing(null)}><X size={18}/></button></div><dl className="reversal-source"><div><dt>รายการเดิม</dt><dd>{expenseLabels[reversing.expenseType]}</dd></div><div><dt>เอกสารอ้างอิง</dt><dd><code>{reversing.sourceExpenseId}</code></dd></div><div><dt>ผลของการแก้กลับ</dt><dd>+{money(reversing.amountMinor)}</dd></div></dl><form onSubmit={submitReversal}><p className="system-reference-note">ระบบจะสร้างรหัสรายการแก้กลับและผูกกับรายการเดิมให้อัตโนมัติ</p><div className="financial-event-fields"><label>วันที่แก้กลับ<input type="date" value={reversalDate} max="2100-12-31" required disabled={reversalBusy} onChange={e=>setReversalDate(e.target.value)}/></label><label>เหตุผลที่แก้กลับ<input ref={reversalNoteRef} value={reversalNote} minLength={3} maxLength={500} required placeholder="เช่น บันทึกใบเสร็จซ้ำ" disabled={reversalBusy} onChange={e=>setReversalNote(e.target.value)}/></label></div><label className="checkbox-label financial-scope-confirm"><input type="checkbox" checked={reversalConfirmed} disabled={reversalBusy} onChange={e=>setReversalConfirmed(e.target.checked)}/>ฉันยืนยันว่าต้องการยกเลิกผลของรายการนี้ โดยเก็บรายการเดิมไว้ในประวัติ</label>{reversalError&&<p className="notice error" role="alert">{reversalError}</p>}<div className="form-actions"><button type="button" className="button secondary" disabled={reversalBusy} onClick={()=>setReversing(null)}>ยกเลิก</button><button type="submit" className="button primary" disabled={reversalBusy||!reversalConfirmed||!reversalDate||reversalNote.trim().length<3}>{reversalBusy?'กำลังแก้กลับ…':'ยืนยันการแก้กลับ'}</button></div></form></section>}
    {!ledger.items.length?<section className="panel empty-state adjustment-empty"><CheckCircle2 size={30}/><h2>ยังไม่มีค่าใช้จ่ายที่บันทึก</h2><p>เริ่มจากค่าใช้จ่ายที่มีผลต่อเงินเหลือของร้านมากที่สุด เช่น ค่าโฆษณาและเงินเดือน</p></section>:<section className="panel table-panel adjustment-history"><div className="panel-heading adjustment-heading"><div><h2>ประวัติค่าใช้จ่าย</h2><p className="field-help">ล่าสุด {ledger.limit} รายการ · รายการเดิมจะไม่ถูกแก้ไขหรือลบ</p></div></div><div className="table-scroll adjustment-desktop"><table><thead><tr><th>วันที่ / หมวด</th><th className="numeric">จำนวนเงิน</th><th>ขอบเขต</th><th>สถานะ</th><th>หลักฐาน</th>{canWrite&&<th>การทำงาน</th>}</tr></thead><tbody>{ledger.items.map(item=><tr key={item.id}><td><strong>{item.reversesExpenseId?'แก้กลับ · ':''}{expenseLabels[item.expenseType]}</strong><small>{date(item.occurredOn)}</small></td><td className={`numeric ${item.reversesExpenseId?'':'text-error'}`}>{item.reversesExpenseId?'+':'-'}{money(item.amountMinor)}</td><td>{item.allocationScope==='shop_direct'?'ร้านนี้โดยตรง':'แบ่งจากส่วนกลาง'}{item.allocationBasis&&<small>{item.allocationBasis}</small>}</td><td className="adjustment-status"><ExpenseStatus item={item}/></td><td className="adjustment-evidence"><strong>{item.note}</strong><code>{item.sourceExpenseId}</code></td>{canWrite&&<td>{!item.reversesExpenseId&&!item.reversedByExpenseId?<button type="button" className="text-button reversal-action" onClick={()=>selectReversal(item)}><RotateCcw size={15}/>แก้กลับรายการ</button>:<span className="muted">—</span>}</td>}</tr>)}</tbody></table></div><div className="adjustment-mobile-list">{ledger.items.map(item=><article className="adjustment-card" key={item.id}><header><div><strong>{item.reversesExpenseId?'แก้กลับ · ':''}{expenseLabels[item.expenseType]}</strong><small>{date(item.occurredOn)}</small></div><strong className={item.reversesExpenseId?'':'text-error'}>{item.reversesExpenseId?'+':'-'}{money(item.amountMinor)}</strong></header><div className="adjustment-card-status"><ExpenseStatus item={item}/></div><dl><div><dt>ขอบเขต</dt><dd>{item.allocationScope==='shop_direct'?'ร้านนี้โดยตรง':'แบ่งจากส่วนกลาง'}</dd></div><div><dt>หลักฐาน</dt><dd>{item.note}</dd></div>{item.allocationBasis&&<div><dt>วิธีแบ่ง</dt><dd>{item.allocationBasis}</dd></div>}</dl><code className="adjustment-card-reference">{item.sourceExpenseId}</code>{canWrite&&!item.reversesExpenseId&&!item.reversedByExpenseId&&<button type="button" className="button secondary adjustment-card-action" onClick={()=>selectReversal(item)}><RotateCcw size={16}/>แก้กลับรายการ</button>}</article>)}</div></section>}
    <p className="review-footnote">ยอดนี้ช่วยให้เห็นเงินเหลือหลังค่าใช้จ่ายที่บันทึก แต่ยังไม่ใช่กำไรสุทธิทางบัญชีหรือยอดเงินในธนาคาร</p>
  </>;
}
