'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { ArrowRight,CheckCircle2 } from 'lucide-react';
import type { FinancialEventLedger,FinancialEventType } from '@commerce/finance';
import { money,request,toMinor } from '../lib/client';

const labels:Record<FinancialEventType,string>={refund:'คืนเงินให้ลูกค้า',fee_rebate:'เครดิตค่าธรรมเนียมคืน'};
const date=(value:string)=>new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date(`${value}T00:00:00+07:00`));

export function FinancialEventWorkspace({tenantId,shopId,shopName,canWrite,today,ledger}:{tenantId:string;shopId:string;shopName:string;canWrite:boolean;today:string;ledger:FinancialEventLedger}){
  const router=useRouter(),[eventType,setEventType]=useState<FinancialEventType>('refund'),[sourceEventId,setSourceEventId]=useState(''),[orderId,setOrderId]=useState(''),[occurredOn,setOccurredOn]=useState(today),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
  async function submit(event:React.FormEvent){
    event.preventDefault();setError('');setSaved('');setBusy(true);
    try{
      const amountMinor=toMinor(amount.trim());if(amountMinor<=0)throw new Error('จำนวนเงินต้องมากกว่า 0 บาท');
      const result=await request<{duplicate:boolean;matchedLineCount:number}>(`/api/tenants/${tenantId}/financial-events`,{shopId,sourceEventId:sourceEventId.trim(),orderId:orderId.trim(),eventType,occurredOn,amountMinor,note:note.trim(),confirmedOutsideImportedReceipt:confirmed});
      setSaved(result.duplicate?'รายการต้นทางนี้ถูกบันทึกไว้แล้ว ระบบไม่ได้เพิ่มยอดซ้ำ':result.matchedLineCount?`บันทึกรายการแล้ว จับคู่กับคำสั่งซื้อ ${orderId.trim()} จำนวน ${result.matchedLineCount} รายการ`:`บันทึกรายการแล้ว แต่ยังไม่พบคำสั่งซื้อ ${orderId.trim()} รายการนี้รอตรวจสอบและยังไม่รวมในยอดที่จับคู่แล้ว`);
      if(!result.duplicate){setSourceEventId('');setOrderId('');setAmount('');setNote('');setConfirmed(false);}router.refresh();
    }catch(e){setError(e instanceof Error?e.message:'บันทึกรายการไม่สำเร็จ');}finally{setBusy(false);}
  }
  return <>
    <div className="page-heading"><div><h1>คืนเงินและปรับยอด</h1><p>{shopName} · เหตุการณ์หลังการขายที่อยู่นอกยอดเงินรับในไฟล์เดิม</p></div><Link className="button secondary" href="/performance">ดูผลต่อเงินรับ <ArrowRight size={16}/></Link></div>
    <section className="summary-strip adjustment-overview" aria-label="สรุปรายการปรับยอด"><div><span>รายการทั้งหมด</span><strong>{ledger.summary.total}<small>รายการ</small></strong></div><div><span>จับคู่คำสั่งซื้อแล้ว</span><strong>{ledger.summary.matched}<small>รายการ</small></strong></div><div><span>รอตรวจสอบ</span><strong className={ledger.summary.unmatched?'text-error':''}>{ledger.summary.unmatched}<small>รายการ</small></strong></div><div><span>ผลต่อเงินรับที่จับคู่แล้ว</span><strong className={ledger.summary.netAdjustmentMinor<0?'text-error':''}>{ledger.summary.netAdjustmentMinor>=0?'+':''}{money(ledger.summary.netAdjustmentMinor)}</strong></div></section>
    {ledger.summary.unmatched>0&&<p className="notice error"><strong>มี {ledger.summary.unmatched} รายการที่ยังไม่พบคำสั่งซื้อ</strong><br/>ระบบเก็บหลักฐานไว้ แต่ยังไม่รวมรายการเหล่านี้ในยอดเงินรับที่จับคู่แล้ว กรุณาตรวจเลขคำสั่งซื้อหรือรอนำเข้ารายการขายต้นทาง</p>}
    {!canWrite&&<p className="notice">สิทธิ์ผู้ตรวจสอบเปิดดูรายการและหลักฐานได้ การบันทึกรายการใหม่ต้องใช้สิทธิ์เจ้าของหรือการเงิน</p>}
    {canWrite&&<section className="panel financial-event-entry"><div><h2>บันทึกเหตุการณ์</h2><p className="field-help">ใช้เฉพาะยอดคืนเงินหรือเครดิตที่เกิดหลังข้อมูลขายเดิมและยังไม่รวมใน “เงินรับสุทธิ” ที่นำเข้าแล้ว ระบบจะไม่แก้รายการขายเดิม</p></div><form onSubmit={submit}><div className="financial-event-fields"><label>ประเภทเหตุการณ์<select value={eventType} disabled={busy} onChange={e=>setEventType(e.target.value as FinancialEventType)}><option value="refund">คืนเงินให้ลูกค้า</option><option value="fee_rebate">เครดิตค่าธรรมเนียมคืน</option></select></label><label>วันที่เกิดเหตุการณ์<input type="date" value={occurredOn} max="2100-12-31" required disabled={busy} onChange={e=>setOccurredOn(e.target.value)}/></label><label>รหัสรายการต้นทาง<input aria-label="รหัสรายการต้นทาง" value={sourceEventId} maxLength={150} required placeholder="เช่น REFUND-20260916-001" disabled={busy} onChange={e=>setSourceEventId(e.target.value)}/><span className="field-help">ต้องคงที่และไม่ซ้ำต่อร้าน เพื่อป้องกันบันทึกซ้ำ</span></label><label>เลขคำสั่งซื้อ<input value={orderId} maxLength={100} required placeholder="เลขเดียวกับรายงานยอดขาย" disabled={busy} onChange={e=>setOrderId(e.target.value)}/></label><label>จำนวนเงิน (บาท)<input aria-label="จำนวนเงิน (บาท)" inputMode="decimal" value={amount} required placeholder="0.00" disabled={busy} onChange={e=>setAmount(e.target.value)}/><span className="field-help">กรอกเป็นจำนวนบวก ระบบกำหนดเครื่องหมายจากประเภทเหตุการณ์</span></label><label className="full-width">เหตุผลหรือหลักฐาน<input value={note} minLength={3} maxLength={500} required placeholder="เช่น ลูกค้าได้รับคืนบางส่วนและยังเก็บสินค้า" disabled={busy} onChange={e=>setNote(e.target.value)}/></label></div><label className="checkbox-label financial-scope-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>ฉันตรวจแล้วว่ายอดนี้ยังไม่รวมอยู่ในเงินรับสุทธิที่นำเข้าไว้ จึงไม่ทำให้หักหรือบวกซ้ำ</label>{error&&<p className="notice error" role="alert">{error}</p>}{saved&&<p className="notice success" role="status">{saved}</p>}<div className="form-actions"><button type="submit" className="button primary" disabled={busy||!confirmed||!sourceEventId.trim()||!orderId.trim()||!occurredOn||!amount.trim()||note.trim().length<3}>{busy?'กำลังบันทึก…':'บันทึกรายการปรับยอด'}</button></div></form></section>}
    {!ledger.items.length?<section className="panel empty-state adjustment-empty"><CheckCircle2 size={30}/><h2>ยังไม่มีรายการปรับยอด</h2><p>เมื่อเกิด refund หรือเครดิตค่าธรรมเนียมหลังการขาย รายการที่บันทึกจะแสดงพร้อมสถานะการจับคู่ที่นี่</p></section>:<section className="panel table-panel adjustment-history"><div className="panel-heading adjustment-heading"><div><h2>ประวัติรายการปรับยอด</h2><p className="field-help">ล่าสุด {ledger.limit} รายการ · ข้อมูลเป็น append-only</p></div></div><div className="table-scroll"><table><thead><tr><th>วันที่ / ประเภท</th><th>คำสั่งซื้อ</th><th className="numeric">จำนวนเงิน</th><th>สถานะจับคู่</th><th>หลักฐาน</th></tr></thead><tbody>{ledger.items.map(item=><tr key={item.id}><td><strong>{labels[item.eventType]}</strong><small>{date(item.occurredOn)}</small></td><td><code>{item.orderId}</code></td><td className={`numeric ${item.eventType==='refund'?'text-error':''}`}>{item.eventType==='refund'?'-':'+'}{money(item.amountMinor)}</td><td>{item.matchedLineCount?<span className="pill green">จับคู่ {item.matchedLineCount} รายการ</span>:<span className="pill amber">รอตรวจสอบ</span>}</td><td className="adjustment-evidence"><strong>{item.note}</strong><code>{item.sourceEventId}</code></td></tr>)}</tbody></table></div></section>}
    <p className="review-footnote">การแก้รายการที่บันทึกผิดต้องเพิ่ม reversing event ใหม่ในรุ่นถัดไป รุ่นนี้จึงไม่เปิดแก้ไขหรือลบประวัติ</p>
  </>;
}
