'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { LayoutDashboard,Package,Sparkles,Users,History,ChevronDown,FileInput,ChartNoAxesCombined,ClipboardCheck,ReceiptText,WalletCards } from 'lucide-react';
import { switchOrganization,switchShop } from '../app/actions';
import type { Role } from '@commerce/contracts';
const financialRoles:Role[]=['owner','finance','auditor'];
const links=[{href:'/',label:'ภาพรวม',icon:LayoutDashboard},{href:'/catalog',label:'สินค้า',icon:Package},{href:'/imports',label:'นำเข้ารายงาน',icon:FileInput,roles:financialRoles},{href:'/financial-events',label:'คืนเงินและปรับยอด',icon:ReceiptText,roles:financialRoles},{href:'/expenses',label:'ค่าใช้จ่ายร้าน',icon:WalletCards,roles:financialRoles},{href:'/reviews',label:'รายการที่ต้องตรวจ',icon:ClipboardCheck,roles:financialRoles},{href:'/performance',label:'เงินรับและต้นทุน',icon:ChartNoAxesCombined,roles:financialRoles},{href:'/ai',label:'วิเคราะห์ข้อมูล',icon:Sparkles},{href:'/team',label:'ทีมและสิทธิ์',icon:Users,roles:['owner'] as Role[]},{href:'/activity',label:'ประวัติการทำงาน',icon:History,roles:['owner','auditor'] as Role[]}];
export function Navigation({role}:{role:Role}){const path=usePathname();return <nav className="nav-links">{links.filter(l=>!l.roles||l.roles.includes(role)).map(l=><Link key={l.href} href={l.href} aria-current={(path===l.href||(l.href!=='/'&&path.startsWith(l.href+'/')))?'page':undefined} className={(path===l.href||(l.href!=='/'&&path.startsWith(l.href+'/')))?'active':''}><l.icon size={19}/>{l.label}</Link>)}</nav>;}
export function WorkspacePicker({orgs,current,shops,shopId}:{orgs:{id:string;name:string}[];current:string;shops:{id:string;name:string}[];shopId?:string}){return <div className="workspace-pickers"><form action={switchOrganization}><label className="select-wrap"><span className="sr-only">เลือกบริษัท</span><select name="tenantId" aria-label="เลือกบริษัท" value={current} onChange={e=>e.currentTarget.form?.requestSubmit()}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select><ChevronDown size={14}/></label></form><span className="picker-slash">/</span>{shops.length?<form action={switchShop}><input type="hidden" name="tenantId" value={current}/><label className="select-wrap secondary"><span className="sr-only">เลือกร้านค้า</span><select name="shopId" aria-label="เลือกร้านค้า" value={shopId} onChange={e=>e.currentTarget.form?.requestSubmit()}>{shops.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><ChevronDown size={14}/></label></form>:<span className="muted">ยังไม่มีร้านค้า</span>}</div>;}
