'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect,useRef,useState } from 'react';
import { ArrowRight,CheckCircle2,RotateCcw,X } from 'lucide-react';
import type { SettlementLedger,SettlementLineItem } from '@commerce/finance';
import { money,request,toMinor } from '../lib/client';

const date=(value:string)=>new Intl.DateTimeFormat('th-TH',{dateStyle:'medium',timeZone:'Asia/Bangkok'}).format(new Date(`${value}T00:00:00+07:00`));
const signedAmount=(item:SettlementLineItem)=>item.reversesLineId?-item.amountMinor:item.amountMinor;

function LineStatus({item}:{item:SettlementLineItem}){
  if(item.reversesLineId)return <span className="pill neutral">รายการแก้กลับ</span>;
  if(item.reversedByLineId)return <span className="pill neutral">ถูกแก้กลับแล้ว</span>;
  return item.matched?<span className="pill green">พบคำสั่งซื้อ</span>:<span className="pill amber">ไม่พบคำสั่งซื้อ</span>;
}

export function SettlementWorkspace({tenantId,shopId,shopName,canWrite,today,ledger}:{tenantId:string;shopId:string;shopName:string;canWrite:boolean;today:string;ledger:SettlementLedger}){
  const router=useRouter(),[payoutReference,setPayoutReference]=useState(''),[settledOn,setSettledOn]=useState(today),[payoutTotal,setPayoutTotal]=useState(''),[sourceLineId,setSourceLineId]=useState(''),[orderId,setOrderId]=useState(''),[amount,setAmount]=useState(''),[note,setNote]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
  const [reversing,setReversing]=useState<SettlementLineItem|null>(null),[reversalNote,setReversalNote]=useState(''),[reversalConfirmed,setReversalConfirmed]=useState(false),[reversalBusy,setReversalBusy]=useState(false),[reversalError,setReversalError]=useState(''),[reversalSaved,setReversalSaved]=useState('');
  const reversalNoteRef=useRef<HTMLInputElement>(null);

  useEffect(()=>{if(reversing){document.getElementById('settlement-reversal')?.scrollIntoView({block:'center'});reversalNoteRef.current?.focus();}},[reversing]);

  async function submit(event:React.FormEvent){
    event.preventDefault();setError('');setSaved('');setBusy(true);
    try{
      const payoutTotalMinor=toMinor(payoutTotal.trim()),amountMinor=toMinor(amount.trim());
      if(payoutTotalMinor<=0||amountMinor<=0)throw new Error('ยอดเงินต้องมากกว่า 0 บาท');
      const result=await request<{duplicate:boolean;matchedLineCount:number}>(`/api/tenants/${tenantId}/settlements`,{shopId,sourceLineId:sourceLineId.trim(),payoutReference:payoutReference.trim(),orderId:orderId.trim(),settledOn,payoutTotalMinor,amountMinor,note:note.trim(),confirmedStatement:confirmed});
      setSaved(result.duplicate?'บรรทัดต้นทางนี้ถูกบันทึกไว้แล้ว ระบบไม่ได้เพิ่มยอดซ้ำ':result.matchedLineCount?`บันทึกแล้วและพบคำสั่งซื้อ ${orderId.trim()}`:`บันทึกแล้ว แต่ยังไม่พบคำสั่งซื้อ ${orderId.trim()} รายการนี้ยังต้องตรวจ`);
      if(!result.duplicate){setSourceLineId('');setOrderId('');setAmount('');setNote('');setConfirmed(false);}router.refresh();
    }catch(e){setError(e instanceof Error?e.message:'บันทึกบรรทัดเงินโอนไม่สำเร็จ');}finally{setBusy(false);}
  }

  function selectReversal(item:SettlementLineItem){setReversing(item);setReversalNote('');setReversalConfirmed(false);setReversalError('');setReversalSaved('');}
  async function submitReversal(event:React.FormEvent){
    event.preventDefault();if(!reversing)return;setReversalError('');setReversalSaved('');setReversalBusy(true);
    try{
      const result=await request<{duplicate:boolean}>(`/api/tenants/${tenantId}/settlements/${reversing.id}/reverse`,{shopId,note:reversalNote.trim(),confirmedCorrection:reversalConfirmed});
      setReversalSaved(result.duplicate?'รายการแก้กลับนี้มีอยู่แล้ว ระบบไม่ได้หักซ้ำ':`แก้กลับบรรทัด ${reversing.sourceLineId} แล้ว โดยยังเก็บรายการเดิมไว้`);setReversing(null);router.refresh();
    }catch(e){setReversalError(e instanceof Error?e.message:'แก้กลับบรรทัดเงินโอนไม่สำเร็จ');}finally{setReversalBusy(false);}
  }

  return <>
    <div className="page-heading"><div><h1>กระทบยอดเงินโอน</h1><p>{shopName} · เทียบ statement การโอนกับคำสั่งซื้อที่นำเข้าแล้ว</p></div><Link className="button secondary" href="/performance">ดูเงินรับและต้นทุน <ArrowRight size={16}/></Link></div>
    <section className="summary-strip settlement-overview" aria-label="สรุปการกระทบยอด"><div><span>รอบโอนทั้งหมด</span><strong>{ledger.summary.payoutCount}<small>รอบ</small></strong></div><div><span>จัดสรรครบและจับคู่แล้ว</span><strong>{ledger.summary.balancedPayoutCount}<small>รอบ</small></strong></div><div><span>รอบที่ต้องตรวจ</span><strong className={ledger.summary.unresolvedPayoutCount?'text-error':''}>{ledger.summary.unresolvedPayoutCount}<small>รอบ</small></strong></div><div><span>ยอดโอนตามรายงาน</span><strong>{money(ledger.summary.reportedPayoutMinor)}</strong></div></section>
    {reversalSaved&&<p className="notice success" role="status">{reversalSaved}</p>}
    {(ledger.summary.unmatchedLineCount>0||ledger.summary.unresolvedPayoutCount>0)&&<p className="notice"><strong>ยังมีกระทบยอดที่ต้องตรวจ</strong><br/>{ledger.summary.unmatchedLineCount?`${ledger.summary.unmatchedLineCount} บรรทัดยังไม่พบคำสั่งซื้อ · `:''}รอบโอนที่ยอดจัดสรรยังไม่เท่ายอดรวมจะไม่ถูกระบุว่าเสร็จ</p>}
    {!canWrite&&<p className="notice">สิทธิ์ผู้ตรวจสอบเปิดดูยอดและหลักฐานได้ การเพิ่มหรือแก้กลับรายการต้องใช้สิทธิ์เจ้าของหรือการเงิน</p>}
    {canWrite&&<section className="panel settlement-entry"><div><h2>เพิ่มบรรทัดจาก statement</h2><p className="field-help">หนึ่งรอบโอนมีหลายคำสั่งซื้อได้ และหนึ่งคำสั่งซื้ออาจได้รับเงินหลายรอบ กรอกหนึ่งบรรทัดต่อ allocation จากเอกสารต้นทาง</p></div><form onSubmit={submit}><div className="settlement-fields"><label>รหัสรอบโอน<input aria-label="รหัสรอบโอน" value={payoutReference} maxLength={150} required placeholder="เช่น PAYOUT-202609-001" disabled={busy} onChange={e=>setPayoutReference(e.target.value)}/><span className="field-help">ใช้ค่าเดิมทุกบรรทัดในรอบโอนเดียวกัน</span></label><label>วันที่โอน<input aria-label="วันที่โอน" type="date" value={settledOn} max="2100-12-31" required disabled={busy} onChange={e=>setSettledOn(e.target.value)}/></label><label>ยอดโอนรวมตามรายงาน (บาท)<input aria-label="ยอดโอนรวมตามรายงาน (บาท)" inputMode="decimal" value={payoutTotal} required placeholder="0.00" disabled={busy} onChange={e=>setPayoutTotal(e.target.value)}/><span className="field-help">ยอดรวมนี้ต้องตรงกันทุกบรรทัดในรอบเดียวกัน</span></label><label>รหัสบรรทัดต้นทาง<input aria-label="รหัสบรรทัดต้นทาง" value={sourceLineId} maxLength={150} required placeholder="เช่น PAYOUT-LINE-001" disabled={busy} onChange={e=>setSourceLineId(e.target.value)}/><span className="field-help">ต้องคงที่และไม่ซ้ำ เพื่อป้องกันบันทึกซ้ำ</span></label><label>เลขคำสั่งซื้อ<input aria-label="เลขคำสั่งซื้อสำหรับกระทบยอด" value={orderId} maxLength={100} required placeholder="เลขเดียวกับรายงานยอดขาย" disabled={busy} onChange={e=>setOrderId(e.target.value)}/></label><label>ยอดที่จัดสรรให้คำสั่งซื้อนี้ (บาท)<input aria-label="ยอดที่จัดสรรให้คำสั่งซื้อนี้ (บาท)" inputMode="decimal" value={amount} required placeholder="0.00" disabled={busy} onChange={e=>setAmount(e.target.value)}/></label><label className="full-width">หลักฐานหรือหมายเหตุ<input aria-label="หลักฐานหรือหมายเหตุการโอน" value={note} minLength={3} maxLength={500} required placeholder="เช่น Statement รอบวันที่ 1–15 ก.ย." disabled={busy} onChange={e=>setNote(e.target.value)}/></label></div><label className="checkbox-label settlement-confirm"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>ฉันตรวจแล้วว่ารหัสรอบโอน ยอดรวม และ allocation นี้มาจาก statement เดียวกัน</label>{error&&<p className="notice error" role="alert">{error}</p>}{saved&&<p className="notice success" role="status">{saved}</p>}<div className="form-actions"><button type="submit" className="button primary" disabled={busy||!confirmed||!payoutReference.trim()||!settledOn||!payoutTotal.trim()||!sourceLineId.trim()||!orderId.trim()||!amount.trim()||note.trim().length<3}>{busy?'กำลังบันทึก…':'บันทึกบรรทัดเงินโอน'}</button></div></form></section>}
    {canWrite&&reversing&&<section className="panel reversal-entry" id="settlement-reversal" aria-labelledby="settlement-reversal-heading"><div className="reversal-heading"><div><span className="eyebrow">แก้ไขโดยไม่ลบประวัติ</span><h2 id="settlement-reversal-heading">แก้กลับบรรทัดเงินโอน</h2><p>ระบบจะหัก allocation {money(reversing.amountMinor)} จากรอบ <code>{reversing.payoutReference}</code></p></div><button type="button" className="icon-button" aria-label="ยกเลิกการแก้กลับเงินโอน" disabled={reversalBusy} onClick={()=>setReversing(null)}><X size={18}/></button></div><dl className="reversal-source"><div><dt>บรรทัดเดิม</dt><dd><code>{reversing.sourceLineId}</code></dd></div><div><dt>คำสั่งซื้อ</dt><dd><code>{reversing.orderId}</code></dd></div><div><dt>ผลของรายการแก้กลับ</dt><dd>-{money(reversing.amountMinor)}</dd></div></dl><form onSubmit={submitReversal}><p className="system-reference-note">ระบบจะสร้างรหัสอ้างอิงรายการแก้กลับและผูกกับบรรทัดเดิมให้อัตโนมัติ</p><label>เหตุผลที่แก้กลับ<input ref={reversalNoteRef} aria-label="เหตุผลที่แก้กลับเงินโอน" value={reversalNote} minLength={3} maxLength={500} required placeholder="เช่น เลือกเลขคำสั่งซื้อผิด" disabled={reversalBusy} onChange={e=>setReversalNote(e.target.value)}/></label><label className="checkbox-label settlement-confirm"><input type="checkbox" checked={reversalConfirmed} disabled={reversalBusy} onChange={e=>setReversalConfirmed(e.target.checked)}/>ฉันยืนยันว่าต้องการยกเลิกผลของบรรทัดนี้ โดยเก็บรายการเดิมไว้ในประวัติ</label>{reversalError&&<p className="notice error" role="alert">{reversalError}</p>}<div className="form-actions"><button type="button" className="button secondary" disabled={reversalBusy} onClick={()=>setReversing(null)}>ยกเลิก</button><button type="submit" className="button primary" disabled={reversalBusy||!reversalConfirmed||reversalNote.trim().length<3}>{reversalBusy?'กำลังแก้กลับ…':'ยืนยันการแก้กลับ'}</button></div></form></section>}
    {!ledger.payouts.length?<section className="panel empty-state settlement-empty"><CheckCircle2 size={30}/><h2>ยังไม่มีข้อมูลรอบโอน</h2><p>เพิ่มบรรทัดจาก statement เพื่อดูว่ายอดจัดสรรครบและจับคู่คำสั่งซื้อได้หรือไม่</p></section>:<div className="settlement-grid"><section className="panel table-panel"><div className="panel-heading settlement-heading"><div><h2>รอบโอน</h2><p className="field-help">ยอดต่าง = ยอดจัดสรร − ยอดโอนรวมตามรายงาน</p></div></div><div className="table-scroll"><table><thead><tr><th>รอบโอน / วันที่</th><th className="numeric">ยอดตามรายงาน</th><th className="numeric">จัดสรรแล้ว</th><th className="numeric">ยอดต่าง</th><th>สถานะ</th></tr></thead><tbody>{ledger.payouts.map(row=><tr key={row.payoutReference}><td><code>{row.payoutReference}</code><small>{date(row.settledOn)}</small></td><td className="numeric">{money(row.payoutTotalMinor)}</td><td className="numeric">{money(row.allocatedMinor)}</td><td className={`numeric ${row.differenceMinor?'text-error':''}`}>{row.differenceMinor>=0?'+':''}{money(row.differenceMinor)}</td><td>{row.differenceMinor===0&&!row.unmatchedLineCount?<span className="pill green">กระทบครบ</span>:<span className="payout-issues"><span className="pill amber">ต้องตรวจ</span><small>{row.activeLineCount} บรรทัด{row.unmatchedLineCount?` · ไม่พบออเดอร์ ${row.unmatchedLineCount}`:''}</small></span>}</td></tr>)}</tbody></table></div></section>
      <section className="panel table-panel"><div className="panel-heading settlement-heading"><div><h2>เทียบตามคำสั่งซื้อ</h2><p className="field-help">ยอดที่ควรได้รับรวม refund และเครดิตค่าธรรมเนียมที่บันทึกแล้ว</p></div></div>{ledger.orders.length?<div className="table-scroll"><table><thead><tr><th>คำสั่งซื้อ</th><th className="numeric">ควรได้รับ</th><th className="numeric">ได้รับตาม statement</th><th className="numeric">ยอดต่าง</th><th>สถานะ</th></tr></thead><tbody>{ledger.orders.map(row=><tr key={row.orderId}><td><code>{row.orderId}</code><small>{row.settlementLineCount} บรรทัดที่ยังมีผล</small></td><td className="numeric">{money(row.expectedReceiptMinor)}</td><td className="numeric">{money(row.settledMinor)}</td><td className={`numeric ${row.differenceMinor?'text-error':''}`}>{row.differenceMinor>=0?'+':''}{money(row.differenceMinor)}</td><td>{row.differenceMinor===0?<span className="pill green">ตรงกัน</span>:<span className="pill amber">ต้องตรวจ</span>}</td></tr>)}</tbody></table></div>:<p className="quiet-empty">ยังไม่มีบรรทัดที่จับคู่คำสั่งซื้อได้</p>}</section></div>}
    {!!ledger.items.length&&<section className="panel table-panel settlement-history"><div className="panel-heading settlement-heading"><div><h2>หลักฐานบรรทัดเงินโอน</h2><p className="field-help">ล่าสุด {ledger.limit} รายการ · ข้อมูลเป็น append-only</p></div></div><div className="table-scroll settlement-desktop"><table><thead><tr><th>รอบโอน / บรรทัด</th><th>คำสั่งซื้อ</th><th className="numeric">Allocation</th><th>สถานะ</th><th>หลักฐาน</th>{canWrite&&<th>การทำงาน</th>}</tr></thead><tbody>{ledger.items.map(item=>{const signed=signedAmount(item);return <tr key={item.id}><td><strong>{item.reversesLineId?'แก้กลับ · ':''}{item.payoutReference}</strong><code>{item.sourceLineId}</code><small>{date(item.settledOn)}</small></td><td><code>{item.orderId}</code></td><td className={`numeric ${signed<0?'text-error':''}`}>{signed>=0?'+':'-'}{money(Math.abs(signed))}</td><td><LineStatus item={item}/></td><td className="settlement-evidence">{item.note}</td>{canWrite&&<td>{!item.reversesLineId&&!item.reversedByLineId?<button type="button" className="text-button reversal-action" onClick={()=>selectReversal(item)}><RotateCcw size={15}/>แก้กลับบรรทัด</button>:<span className="muted">—</span>}</td>}</tr>;})}</tbody></table></div><div className="settlement-mobile-list">{ledger.items.map(item=>{const signed=signedAmount(item);return <article className="settlement-card" key={item.id}><header><div><strong>{item.reversesLineId?'แก้กลับ · ':''}{item.payoutReference}</strong><code>{item.sourceLineId}</code></div><strong className={signed<0?'text-error':''}>{signed>=0?'+':'-'}{money(Math.abs(signed))}</strong></header><LineStatus item={item}/><dl><div><dt>คำสั่งซื้อ</dt><dd><code>{item.orderId}</code></dd></div><div><dt>วันที่โอน</dt><dd>{date(item.settledOn)}</dd></div><div><dt>หลักฐาน</dt><dd>{item.note}</dd></div></dl>{canWrite&&!item.reversesLineId&&!item.reversedByLineId&&<button type="button" className="button secondary" onClick={()=>selectReversal(item)}><RotateCcw size={16}/>แก้กลับบรรทัด</button>}</article>;})}</div></section>}
    <p className="review-footnote">ยอดในหน้านี้มาจาก statement ที่ผู้ใช้ยืนยัน ยังไม่ใช่การตรวจรายการเดินบัญชีธนาคาร และยอดต่างไม่ได้แปลว่าแพลตฟอร์มคำนวณผิดจนกว่าจะตรวจ reserve, timing และเงื่อนไขของรอบโอน</p>
  </>;
}
